version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      build:
        context: btcd/
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-btcd.sh"]

    btcctl:
        extends: btc
        container_name: btcctl
        links:
            - "btcd:rpcserver"
        entrypoint: ["./start-btcctl.sh"]


    # ltfn is an image of litecoinfinance node which used as base image for ltfnd and
    # ltfnctl. The environment variables default values determined on stage of
    # container start within starting script.
    ltfn:
      image: ltfnd
      build:
        context: ltfnd/
      volumes:
            - shared:/rpc
            - litecoinfinance:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    ltfnd:
        extends: ltfn
        container_name: ltfnd
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-ltfnd.sh"]

    ltfnctl:
        extends: ltfn
        container_name: ltfnctl
        links:
            - "ltfnd:rpcserver"
        entrypoint: ["./start-ltfnctl.sh"]

    lnd:
        image: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
        entrypoint: ["./start-lnd.sh"]

    lnd_ltfn:
      extends: lnd
      container_name: lnd_ltfn
      links:
          - "ltfnd:blockchain"

    lnd_btc:
      extends: lnd
      container_name: lnd_btc
      links:
          - "btcd:blockchain"

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  # litecoinfinance volume is needed for maintaining blockchain persistence
  # during ltfnd container recreation.
  litecoinfinance:
    driver: local
